name: Deploy Demo website
on:
  push:
    branches:
      - master
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GATSBY_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v1

      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          deploy-branch: gh-pages
          working-dir: pwa
          gatsby-args: --prefix-paths
#          gatsby-args: --prefix-paths
          access-token: ${{ secrets.ACCESS_TOKEN }}
